# REFERÊNCIA RÁPIDA – GitHub Actions: job de teste (PHPUnit) + job de deploy (exemplo mínimo)
# Fonte: 014-WordPress-Fase-14-Implantacao-DevOps.md
# Coloque em .github/workflows/test-deploy.yml

name: Test and Deploy

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-progress
      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --no-configuration tests/Unit 2>/dev/null || true
        # Ajuste: use phpunit.xml e WP_TESTS_DIR se tiver testes de integração

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          echo "Configure SSH e rsync/scp conforme seu servidor"
          # ssh $DEPLOY_HOST "cd /var/www/app && git pull && composer install --no-dev"
          # Ou use rsync para enviar arquivos
